from enum import IntEnum

class ExitCode(IntEnum):
    SUCCESS = 0
    IRRECOVERABLE_ERROR = -1000
    DATA_FORMAT_ERROR = -1
    BSS_FORMAT_ERROR = -2
    CONSTANT_DECLARATION_ERROR = -3
    NO_START_LABEL = 1
    DUPLICATE_LABEL = 2
    UNOPENABLE_FILE = 4
    STACK_OVERFLOW = 5
    INVALID_INSTRUCTION_SYNTAX = 10
    RESERVED_KEYWORD_VIOLATION = 11
    INVALID_SYSCALL = 12
    NO_EXIT_FOUND = 13
    INVALID_OR_UNSUPPORTED_INSTRUCTION = 14
    SOFTWARE_ERROR = 109101
    # To be continued later